#!/usr/bin/env python3
"""Embed the JS bundle in the debug APK generated by Expo prebuild.

Debug variants skip bundling by default, which makes the app wait for Metro.
Clearing debuggableVariants makes assembleDebug run Expo's export:embed task.
"""

from pathlib import Path
import re
import sys

gradle_path = Path("android/app/build.gradle")
if not gradle_path.is_file():
    sys.exit(f"Missing {gradle_path}. Run expo prebuild first.")

text = gradle_path.read_text()
assignment = re.compile(r"(?m)^(?P<indent>\s*)debuggableVariants\s*=.*$")
uncommented = [
    match
    for match in assignment.finditer(text)
    if not text[: match.start()].rstrip().endswith("//")
    and not match.group(0).lstrip().startswith("//")
]

if uncommented:
    match = uncommented[0]
    text = text[: match.start()] + f"{match.group('indent')}debuggableVariants = []" + text[match.end() :]
elif "autolinkLibrariesWithApp()" not in text:
    sys.exit("Could not find the react { } block in android/app/build.gradle")
else:
    text = text.replace(
        "autolinkLibrariesWithApp()",
        "debuggableVariants = []\n    autolinkLibrariesWithApp()",
        1,
    )

gradle_path.write_text(text)
print("Debug APK will embed the JS bundle (debuggableVariants = []).")
